name: TeleportBow
version: '${project.version}'
main: ml.maxht.teleportbow.TeleportBow
api-version: 1.19
authors: [ Maxhe ]
description: TeleportBow
website: maxht.ml
commands:
  givebow:
    description: Gives a player a teleport bow
    usage: /<command> [playername]
    aliases:
      - teleportbo
      - teleportbow
      - bowtp
      - tpbow
      - shootandtp
      - tpboe
      - tpbo
      - boetp
      - maxhe1

